PARAM_CONFIG_INSTANCE = 'CONFIG_PATH'
PARAM_MQ_URL = 'MQ_URL'
PARAM_CERT_PATH = 'CERT_PATH'
PARAM_KEY_PATH = 'KEY_PATH'
PARAM_CA_PATH = 'CA_PATH'

DOMAINE_SENSEURSPASSIFS = 'SenseursPassifs'
EVENEMENT_DOMAINE_LECTURE = 'lecture'
